# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7673249873c8d7e331ee3d9b796405b497d01f98be1aa354eb37d25eabfbb88e821d293ddf5260f1e4abded4252cfb62ea3e15dce3f93942d9ae7148eaeca46f

test:
  secret_key_base: 307528480814bd692869ed25f70369843e71c2b748f28973aadddaaf6ab29d5b9ad82eba2c8aeabeae7740e55411aeab321353adbee65394cc76f6962cf94cef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
